# -*- coding: utf-8 -*-
"""ML Homework 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w72idBkNPS8XaNZhLTIESudn_7PnTngV
"""

from pandas import read_csv
from matplotlib import pyplot
from statsmodels.tsa.ar_model import AR
from sklearn.metrics import mean_squared_error
from math import sqrt
import pandas as pd
import matplotlib.pyplot as plt  

# load dataset
sorted_countries = ['Russia', 'Greece', 'India', 'United_States_of_America', 'Turkey']
Final = {}

for x in sorted_countries:
  df = pd.read_csv('data.csv')
  country = df[df.countriesAndTerritories == x]
  data = country['cases']
  # split dataset
  X = data.values
  train, test = X[len(X)-1::-1], X[6::-1]

  # train autoregression
  model = AR(train)
  model_fit = model.fit(maxlag=6, disp=False)
  coef = model_fit.params
  window = model_fit.k_ar

  # walk forward over time steps in test
  history = [train[i] for i in range(len(train))]
  predictions = list()
  for t in range(len(test)):
    length = len(history)
    lag = [history[i] for i in range(length-window,length)]
    yhat = coef[0]
    for d in range(window):
      yhat += coef[d+1] * lag[window-d-1]
    obs = test[t]
    predictions.append(yhat)
    history.append(obs)
    print('predicted=%f' % (yhat))
  rmse = sqrt(mean_squared_error(test, predictions))

  # plot
  pyplot.plot(predictions, color='red')
  plt.title('COVID-19 Cases Prediction ' + x, fontsize=14)
  plt.xlabel('Days', fontsize=14)
  plt.ylabel('Cases', fontsize=14)
  plt.grid(True)
  pyplot.show()

  key = x
  Final.setdefault(key, [])
  for items in predictions:
    Final[key].append(round(items))

df = pd.DataFrame(Final, columns = sorted_countries)
df.to_excel (r'107062381_country.xlsx', index = False, header=True)

